name: download

networks:
  proxy:
    name: $NETWORK_NAME
    # external: true

services:
  python:
    build: $PYTHON_IMAGE
    image: code_py
    container_name: python

    command: ["sleep", "infinity"]

    environment:
      THIRD_PARTY_LOGS: $THIRD_PARTY_LOGS
      LOG_LEVEL: $LOG_LEVEL
      ID: ${ID}

    networks:
      proxy:
